{
  "openapi": "3.0.2",
  "info": {
    "title": "Advetorial Api",
    "version": "1"
  },
  "servers": [
    {
      "url": "https://{environtment}.advetorial",
      "variables": {
        "environtment": {
          "default": "dev",
          "enum": ["dev", "qa", "prod"]
        }
      }
    }
  ],
  "paths": {
    "/advetorial": {
      "get": {
        "tags": ["advetorial"],
        "summary": "Ambil semua data advetorial",
        "description": "Dapatkan semua data advetorial",
        "responses": {
          "200": {
            "description": "Sukses mendapatkan semua data advetorial",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/200"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/404"
                },
                "examples": {
                  "failed": {
                    "$ref": "#/components/examples/404"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/advetorial/{id}": {
      "get": {
        "tags": ["advetorial"],
        "summary": "Ambil 1 data advetorial",
        "description": "Ambil 1 data advetorial berdasarkan id",
        "parameters": [
          {
            "$ref": "#/components/parameters/id-advetorial"
          }
        ],
        "responses": {
          "200": {
            "description": "Sukses ambil 1 data advetorial",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200"
                },
                "examples": {
                  "success": {
                    "description": "Contoh response sukses ambil 1 data advetorial",
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Sukses mendapatkan 1 data advetorial",
                      "data": {
                        "post_id": 1,
                        "post_title": "HPN 2023 di Medan, PWI Riau akan Berangkatkan Ratusan WartawanHPN 2023 di Medan, PWI Riau akan Berangkatkan Ratusan Wartawan",
                        "post_category": "acara",
                        "thumbnail": "tes.png",
                        "medium_thumbnail": "tes.png",
                        "post_url": "https://lancangkuning/tes",
                        "post_date": "4 september 2023, senin"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Gagal ambil 1 data advetorial",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/404"
                },
                "examples": {
                  "failed": {
                    "$ref": "#/components/examples/404"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "id-advetorial": {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "id advetorial sebagai parameter",
        "schema": {
          "type": "number",
          "minLength": 1
        }
      }
    },
    "schemas": {
      "200": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "post_id": {
                  "type": "number"
                },
                "post_title": {
                  "type": "string"
                },
                "post_category": {
                  "type": "string"
                },
                "thumbnail": {
                  "type": "string"
                },
                "medium_thumbnail": {
                  "type": "string"
                },
                "post_url": {
                  "type": "string"
                },
                "post_date": {
                  "type": "string"
                }
              },
              "required": ["post_id"]
            }
          }
        }
      },
      "404": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "success": {
            "type": "boolean"
          },
          "errors": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "200": {
        "description": "Contoh response berhasil mendapatkan semua data advetorial",
        "value": {
          "code": 200,
          "success": true,
          "message": "Sukses mendapatkan semua data advetorial",
          "data": [
            {
              "post_id": 1,
              "post_title": "HPN 2023 di Medan, PWI Riau akan Berangkatkan Ratusan WartawanHPN 2023 di Medan, PWI Riau akan Berangkatkan Ratusan Wartawan",
              "post_category": "acara",
              "thumbnail": "tes.png",
              "medium_thumbnail": "tes.png",
              "post_url": "https://lancangkuning/tes",
              "post_date": "4 september 2023, senin"
            },
            {
              "post_id": 2,
              "post_title": "Sedia Payung Sebelum Hujan, Inilah Prakiraan Cuaca Untuk Wilayah Riau",
              "post_category": "cuaca",
              "thumbnail": "tes.png",
              "medium_thumbnail": "tes.png",
              "post_url": "https://lancangkuning/tes",
              "post_date": "5 september 2023, selasa"
            }
          ]
        }
      },
      "404": {
        "description": "Contoh response gagal mendapatkan data",
        "value": {
          "code": 404,
          "success": false,
          "message": "Data yang anda cari tidak ditemukan",
          "details": "Pastikan url yang anda gunakan benar dan data yang anda cari ada didalam sistem."
        }
      }
    }
  }
}
