{
  "openapi": "3.0.2",
  "info": {
    "title": "Tags Api",
    "version": "1"
  },
  "servers": [
    {
      "url": "https://{environtment}.tags",
      "variables": {
        "environtment": {
          "default": "dev",
          "enum": ["dev", "qa", "prod"]
        }
      }
    }
  ],
  "paths": {
    "/tags": {
      "get": {
        "tags": ["tags"],
        "summary": "Ambil semua data tag",
        "description": "Dapatkan semua data tag",
        "responses": {
          "200": {
            "description": "Sukses mendapatkan semua data tag",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200"
                },
                "examples": {
                  "success": {
                    "$ref": "#/components/examples/200"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/404"
                },
                "examples": {
                  "failed": {
                    "$ref": "#/components/examples/404"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/tags/{id}": {
      "get": {
        "tags": ["tags"],
        "summary": "Ambil 1 data tag",
        "description": "Ambil 1 data tag berdasarkan id",
        "parameters": [
          {
            "$ref": "#/components/parameters/id-tags"
          }
        ],
        "responses": {
          "200": {
            "description": "Sukses ambil 1 data tag",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/200"
                },
                "examples": {
                  "success": {
                    "description": "Contoh response sukses ambil 1 data tag",
                    "value": {
                      "code": 200,
                      "success": true,
                      "message": "Sukses mendapatkan 1 data tag",
                      "data": {
                        "tags_id": 1,
                        "tags_name": "sawit"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Gagal ambil 1 data tag",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/404"
                },
                "examples": {
                  "failed": {
                    "$ref": "#/components/examples/404"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {
      "id-tags": {
        "name": "id",
        "in": "path",
        "required": true,
        "description": "id tag sebagai parameter",
        "schema": {
          "type": "number",
          "minLength": 1
        }
      }
    },
    "schemas": {
      "200": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "success": {
            "type": "boolean"
          },
          "message": {
            "type": "string"
          },
          "data": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "tags_id": {
                  "type": "number"
                },
                "tags_name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "required": ["tags_id"]
            }
          }
        }
      },
      "404": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer"
          },
          "success": {
            "type": "boolean"
          },
          "errors": {
            "type": "string"
          }
        }
      }
    },
    "examples": {
      "200": {
        "description": "Contoh response berhasil mendapatkan semua data tag",
        "value": {
          "code": 200,
          "success": true,
          "message": "Sukses mendapatkan semua data tag",
          "data": [
            {
              "tags_id": 1,
              "tags_name": "sawit"
            },
            {
              "tags_id": 2,
              "tags_name": "kampus"
            }
          ]
        }
      },
      "404": {
        "description": "Contoh response gagal mendapatkan data",
        "value": {
          "code": 404,
          "success": false,
          "message": "Data yang anda cari tidak ditemukan",
          "details": "Pastikan url yang anda gunakan benar dan data yang anda cari ada didalam sistem."
        }
      }
    }
  }
}
